name: Session proposal
description: Propose to chair a session at the Global Digital Collaboration Meeting
labels: ["session"]
body:
  - type: markdown
    attributes:
      value: |
        Complete this form to submit a session proposal for the Global Digital Collaboration Meeting.
        Please keep section headings and order intact; tooling parses this issue body.

  - type: markdown
    attributes:
      value: |
        ## A. Core Information

  - type: input
    id: contact_name
    attributes:
      label: Contact Name
      placeholder: Jane Doe
    validations:
      required: true

  - type: input
    id: contact_email
    attributes:
      label: Contact Email
      placeholder: jane@example.org
    validations:
      required: true

  - type: input
    id: session_title
    attributes:
      label: Session Title
      description: Max 120 characters.
      placeholder: Enter session title
    validations:
      required: true

  - type: textarea
    id: co_organizers
    attributes:
      label: Co-Organizers
      description: List all organizations. Minimum 2 required.
      placeholder: |
        1) Organization A
        2) Organization B
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Short Summary
      description: Briefly describe the session topic (max 100 characters).
      placeholder: One-line session summary in simple markdown
    validations:
      required: true

  - type: input
    id: goal
    attributes:
      label: Objectives and Outcomes
      description: What do you hope to achieve? (max 100 characters)
      placeholder: Expected objectives and outcomes
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## B. Session Details

  - type: checkboxes
    id: strategic_alignment
    attributes:
      label: Strategic Alignment with GDC priorities
      description: Select one or more relevant priorities.
      options:
        - label: Age assurance and children’s online safety with interoperable age verification across jurisdictions.
        - label: Trust registries as foundational infrastructure for interoperability.
        - label: Practical interoperability roadmaps and pilots (including digital identity playgrounds).
        - label: Global alignment for ICAO Digital Travel Credential.
        - label: Worldwide interoperability of QEAA attestations (including DTC and mDL).
        - label: Mutual recognition of credentials across jurisdictions.
        - label: Digital health credentials for immunization and workforce use cases.
        - label: DC API.
        - label: Post-quantum ZKP.
        - label: Banking use case for account opening (KYC).
        - label: Global certifications across digital identity ecosystems.
        - label: State sovereignty in digital identity ecosystems.
        - label: Hardware-related interoperability dependencies.
        - label: Trade credentials.
        - label: Long-term outlook for data minimization.
        - label: Selective disclosure and decentralized identifiers.
        - label: Inclusion of developing country needs (offline, multi-device, affordability).
        - label: Privacy-enhancing technologies for KYC and AML.
    validations:
      required: true

  - type: dropdown
    id: public_private_balance
    attributes:
      label: Public/Private Balance
      description: Please indicate whether the speakers represent both sectors.
      options:
        - Yes, includes both public and private sector speakers
        - No, only one sector represented currently
        - To be confirmed
    validations:
      required: false

  - type: textarea
    id: target_audience
    attributes:
      label: Target Audience
      placeholder: Describe the intended audience
    validations:
      required: false

  - type: textarea
    id: chairs
    attributes:
      label: Proposed Speakers and Moderators
      description: Include name, affiliation, and role for each person.
      placeholder: |
        - Name - Affiliation - Role
        - Name - Affiliation - Role
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## C. Logistics

  - type: input
    id: estimated_room_capacity
    attributes:
      label: Estimated Room Capacity
      placeholder: e.g., 50
    validations:
      required: false

  - type: textarea
    id: av_tech_requirements_room_setup
    attributes:
      label: AV/Tech Requirements and Room Setup
      placeholder: Describe audio/visual, technical needs, and room layout.
    validations:
      required: false

  - type: textarea
    id: comments
    attributes:
      label: Additional Information
      placeholder: Any additional context or requests.
    validations:
      required: false
