name: Global Digital Collaboration Meeting Session Registration
description: Register a proposed session for the Global Digital Collaboration Meeting.
title: "[Session Registration]: "
labels:
  - session-registration
body:
  - type: markdown
    attributes:
      value: |
        Complete this form to submit a session proposal for the Global Digital Collaboration Co-Organizers Meeting.

  - type: input
    id: contact_name
    attributes:
      label: Contact Name
      placeholder: Jane Doe
    validations:
      required: true

  - type: input
    id: contact_email
    attributes:
      label: Contact Email
      placeholder: jane@example.org
    validations:
      required: true

  - type: input
    id: session_title
    attributes:
      label: Session Title
      description: Max 120 characters.
      placeholder: Enter session title
    validations:
      required: true

  - type: textarea
    id: co_organizers
    attributes:
      label: Co-Organizers
      description: List all organizations. Minimum 2 required.
      placeholder: |
        1) Organization A
        2) Organization B
    validations:
      required: true

  - type: input
    id: short_summary
    attributes:
      label: Short Summary
      description: Briefly describe the session topic (max 100 characters).
      placeholder: One-line session summary
    validations:
      required: true

  - type: input
    id: objectives_outcomes
    attributes:
      label: Objectives and Outcomes
      description: What do you hope to achieve? (max 100 characters)
      placeholder: Expected objectives and outcomes
    validations:
      required: true

  - type: dropdown
    id: strategic_alignment
    attributes:
      label: "Strategic Alignment: How does this relate to the GDC Council 2026 Priorities?"
      description: Select one or more options.
      multiple: true
      options:
        - Age assurance and children’s online safety as a leading use case, with the objective of developing, in partnership with regulators, a common, interoperable approach to age verification to avoid regulatory and technical fragmentation across jurisdictions.
        - Trust registries as foundational infrastructure for interoperability. Trusted lists, infrastructure, and governance.
        - Development of practical interoperability roadmaps and pilots. Digital identities Playground for interoperability testing
        - Support Global Alignment for the ICAO Digital Passport - (Digital Travel Credential – DTC).
        - Worldwide interoperability of QEAA attestations (i.e., Digital Travel Credential (DTC) and mobile Driver Licence (mDL)
        - Mutual recognition of credentials across jurisdictions, for example, for the mobility of skilled professionals.
        - Digital Health - Verifiable credentials for immunization records and health workforce credentialing.
        - DC API
        - Post-quantum ZKP
        - Banking use case - bank account opening (KYC).
        - Certifications for the various digital identity ecosystems at the global level.
        - State sovereignties in digital identity ecosystems.
        - Hardware
        - Trade credentials
        - Long-term outlook for data minimization.
        - Promote selective disclosure and decentralized identifiers.
        - Ensure developing country needs are included (offline use cases, multi-device realities, affordability).
        - Privacy-enhancing technologies for KYC/AML.
    validations:
      required: true

  - type: dropdown
    id: public_private_balance
    attributes:
      label: Public/Private Balance
      description: Please indicate whether the speakers represent both sectors.
      options:
        - Yes, includes both public and private sector speakers
        - No, only one sector represented currently
        - To be confirmed
    validations:
      required: false

  - type: textarea
    id: target_audience
    attributes:
      label: Target Audience
      placeholder: Describe the intended audience
    validations:
      required: false

  - type: textarea
    id: proposed_speakers_moderators
    attributes:
      label: Proposed Speakers and Moderators
      description: Include name, affiliation, and role for each person.
      placeholder: |
        - Name - Affiliation - Role
        - Name - Affiliation - Role
    validations:
      required: false

  - type: input
    id: estimated_room_capacity
    attributes:
      label: Estimated Room Capacity
      placeholder: e.g., 50
    validations:
      required: false

  - type: textarea
    id: av_tech_requirements_room_setup
    attributes:
      label: AV/Tech Requirements and Room Setup
      placeholder: Describe audio/visual, technical needs, and room layout.
    validations:
      required: false

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      placeholder: Any additional context or requests.
    validations:
      required: false
