name: Global Digital Collaboration Meeting Session Registration
description: Register a proposed session for the Global Digital Collaboration Meeting.
title: "[Session Registration]: "
labels:
  - session-registration
body:
  - type: markdown
    attributes:
      value: |
        Complete this form to submit a session proposal for the Global Digital Collaboration Co-Organizers Meeting.

  - type: input
    id: contact_name
    attributes:
      label: Contact Name
      placeholder: Jane Doe
    validations:
      required: true

  - type: input
    id: contact_email
    attributes:
      label: Contact Email
      placeholder: jane@example.org
    validations:
      required: true

  - type: input
    id: session_title
    attributes:
      label: Session Title
      description: Max 120 characters.
      placeholder: Enter session title
    validations:
      required: true

  - type: textarea
    id: co_organizers
    attributes:
      label: Co-Organizers
      description: List all organizations. Minimum 2 required.
      placeholder: |
        1) Organization A
        2) Organization B
    validations:
      required: true

  - type: input
    id: short_summary
    attributes:
      label: Short Summary
      description: Briefly describe the session topic (max 100 characters).
      placeholder: One-line session summary
    validations:
      required: true

  - type: input
    id: objectives_outcomes
    attributes:
      label: Objectives and Outcomes
      description: What do you hope to achieve? (max 100 characters)
      placeholder: Expected objectives and outcomes
    validations:
      required: true

  - type: input
    id: strategic_alignment
    attributes:
      label: Strategic Alignment
      description: Select one or more GDC Council 2026 priority areas.
      multiple: true
      options:
        - Governance and Trust Infrastructure
        - Interoperability and Cross-jurisdiction Recognition
        - Sectoral Use Cases
        - Privacy and Security
        - Inclusion and Deployment Considerations
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Strategic Alignment guidance**

        - **Governance and Trust Infrastructure**: Trust registries / trusted lists / certification / state sovereignty
        - **Interoperability and Cross-jurisdiction Recognition**: Mutual recognition of credentials; DTC/mDL / QEAA alignment; DC API; interoperability playground
        - **Sectoral Use Cases**: Age assurance; Digital Health; Banking KYC (account opening); Trade credentials; mobility of professionals
        - **Privacy and Security**: Data minimization; selective disclosure; decentralized identifiers; privacy-enhancing tech for KYC/AML; post-quantum ZKP; hardware resilience
        - **Inclusion and Deployment Considerations**: Developing country needs (offline, multi-device, affordability)

  - type: dropdown
    id: public_private_balance
    attributes:
      label: Public/Private Balance
      description: Please indicate whether the speakers represent both sectors.
      options:
        - Yes, includes both public and private sector speakers
        - No, only one sector represented currently
        - To be confirmed
    validations:
      required: false

  - type: textarea
    id: target_audience
    attributes:
      label: Target Audience
      placeholder: Describe the intended audience
    validations:
      required: false

  - type: textarea
    id: proposed_speakers_moderators
    attributes:
      label: Proposed Speakers and Moderators
      description: Include name, affiliation, and role for each person.
      placeholder: |
        - Name - Affiliation - Role
        - Name - Affiliation - Role
    validations:
      required: false

  - type: input
    id: estimated_room_capacity
    attributes:
      label: Estimated Room Capacity
      placeholder: e.g., 50
    validations:
      required: false

  - type: textarea
    id: av_tech_requirements_room_setup
    attributes:
      label: AV/Tech Requirements and Room Setup
      placeholder: Describe audio/visual, technical needs, and room layout.
    validations:
      required: false

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      placeholder: Any additional context or requests.
    validations:
      required: false
